---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create codebuild and codepipeline
Parameters:
  VpcId:
    Description: In which VPC will Codebuild be running
    Type: AWS::EC2::VPC::Id
  SecurityStack:
    Description: Name of an active CloudFormation stack that contains all roles and SGs resources
    Type: String
    Default: Ascending-Security
  PrivateSubnets:
    Description: Private subnets for Codebuild VPC config
    Type: List<AWS::EC2::Subnet::Id>
  Username:
    Description: Database Username
    Type: String
    NoEcho: true
  Password:
    Description: Database Password
    Type: String
    NoEcho: true
Resources:
  UnitTest:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Unit Test before Build and Deployment
      Environment:
        EnvironmentVariables:
          - Name: DB_USERNAME
            Value: !Ref Username
          - Name: DB_URL
            Value: db-test.ascendingdc.com
          - Name: DB_PASSWORD
            Value: !Ref Password
          - Name: DB_NAME
            Value: kris_unit 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: maven:3.6.0-jdk-8
        Type: LINUX_CONTAINER
      Name: 
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - '-UnitTest'
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${SecurityStack}-WorkerNodeSG"
        Subnets: !Ref PrivateSubnets
        VpcId: !Ref VpcId
      ServiceRole: 
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      Source: 
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - apt-get update
                - apt-get install python-dev python-pip -y
                - pip install awscli
            pre_build:
              commands:
                - aws s3 cp s3://ascending-devops/kris_project/application-prod.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/application-dev.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/application-unit.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/share-runtime.properties ./basketball-core/src/main/resources/META-INF/
                - mvn clean compile install -DskipTests=true -q
                - cd basketball-core
                - mvn clean compile install -DskipTests=true -q
            build:
              commands:
                - cd ../basketball-MVC
                - mvn compile flyway:migrate -P unit -Ddb.url=${DB_URL}:5432/${DB_NAME} -Ddb.username=${DB_USERNAME} -Ddb.password=${DB_PASSWORD} -q
                - cd ..
                - mvn compile test -Dspring.profiles.active=unit -Daws.region=us-east-1 -Ddb.url=${DB_URL}:5432/${DB_NAME} -Ddb.username=${DB_USERNAME} -Ddb.password=${DB_PASSWORD} -q
        GitCloneDepth: 1
        Location: https://github.com/xchris1015/basketball.git
        Type: GITHUB
  BuildWarFile:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: no_artifacts
      Description: Build war file
      Environment:
        EnvironmentVariables:
          - Name: DB_USERNAME
            Value: !Ref Username
          - Name: DB_URL
            Value: db-test.ascendingdc.com
          - Name: DB_PASSWORD
            Value: !Ref Password
          - Name: DB_NAME
            Value: kris_unit 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: maven:3.6.0-jdk-8
        Type: LINUX_CONTAINER
      Name: 
        Fn::Join:
          - ''
          - - !Ref AWS::StackName
            - '-BuildWarFile'
      # VpcConfig:
      #   SecurityGroupIds:
      #     - Fn::ImportValue: !Sub "${SecurityStack}-WorkerNodeSG"
      #   Subnets: !Ref PrivateSubnets
      #   VpcId: !Ref VpcId
      ServiceRole: 
        Fn::ImportValue: !Sub "${SecurityStack}-CodeBuildRole"
      Source: 
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - apt-get update
                - apt-get install python-dev python-pip -y
                - pip install awscli
            pre_build:
              commands:
                - aws s3 cp s3://ascending-devops/kris_project/application-prod.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/application-dev.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/application-unit.properties ./basketball-core/src/main/resources/META-INF/env/
                - aws s3 cp s3://ascending-devops/kris_project/share-runtime.properties ./basketball-core/src/main/resources/META-INF/
                - mvn clean compile install -DskipTests=true -q
                - cd basketball-core
                - mvn clean compile install -DskipTests=true -q
            build:
              commands:
                - cd ../basketball-MVC
                - mvn compile flyway:migrate -P unit -Ddb.url=${DB_URL}:5432/${DB_NAME} -Ddb.username=${DB_USERNAME} -Ddb.password=${DB_PASSWORD} -q
                - cd ..
                - mvn compile test -Dspring.profiles.active=unit -Daws.region=us-east-1 -Ddb.url=${DB_URL}:5432/${DB_NAME} -Ddb.username=${DB_USERNAME} -Ddb.password=${DB_PASSWORD} -q
        GitCloneDepth: 1
        Location: https://github.com/xchris1015/basketball.git
        Type: GITHUB